export const FETCH_WEATHER_FOR_CITY = 'FETCH_WEATHER_FOR_CITY';
export const FETCH_WEATHER_FOR_CITY_SUCCESS = 'FETCH_WEATHER_FOR_CITY_SUCCESS';
export const FETCH_WEATHER_FOR_CITY_ERROR = 'FETCH_WEATHER_FOR_CITY_ERROR';